-- Run this in the purchase Supabase SQL editor.
-- Inserts only Firm Name + Item Name + Unit where unit is available.

insert into public.inventory_master (firm_name, item_name, unit)
values
  -- Pmmpl
  ('Pmmpl', '50-50', 'MT'),
  ('Pmmpl', '99 C Fired', 'MT'),
  ('Pmmpl', '99 C Fines', 'MT'),
  ('Pmmpl', 'CBXT 89 (0-1)', 'MT'),
  ('Pmmpl', 'CBXT 89 (1-3)', 'MT'),
  ('Pmmpl', 'CBXT 89 (3-5)', 'MT'),
  ('Pmmpl', 'CBXT 89 (5-8)', 'MT'),
  ('Pmmpl', 'Flyash', 'MT'),
  ('Pmmpl', 'GBXT 76 Fines', 'MT'),
  ('Pmmpl', 'GBXT 76 (0-1)', 'MT'),
  ('Pmmpl', 'GBXT 76 (1-3)', 'MT'),
  ('Pmmpl', 'GBXT 76 (3-5)', 'MT'),
  ('Pmmpl', 'GBXT 76 (5-8)', 'MT'),
  ('Pmmpl', 'GBXT 82 FINES', 'MT'),
  ('Pmmpl', 'GBXT 82 (0-1)', 'MT'),
  ('Pmmpl', 'GBXT 82 (1-3)', 'MT'),
  ('Pmmpl', 'GBXT 82 (3-5)', 'MT'),
  ('Pmmpl', 'GBXT 82 (5-8)', 'MT'),
  ('Pmmpl', 'High Microsilica', 'MT'),
  ('Pmmpl', 'Insulator Lumps', 'MT'),
  ('Pmmpl', 'Insulator (0-1)', 'MT'),
  ('Pmmpl', 'Insulator (1-3)', 'MT'),
  ('Pmmpl', 'Insulator (3-5)', 'MT'),
  ('Pmmpl', 'Katni BXT Fines', 'MT'),
  ('Pmmpl', 'Katni BXT (0-1)', 'MT'),
  ('Pmmpl', 'Katni BXT (1-3)', 'MT'),
  ('Pmmpl', 'Katni BXT (3-5)', 'MT'),
  ('Pmmpl', 'Pyro Fines', 'MT'),
  ('Pmmpl', 'Pyro (0-1)', 'MT'),
  ('Pmmpl', 'Pyro (1-3)', 'MT'),
  ('Pmmpl', 'Pyro (3-5)', 'MT'),
  ('Pmmpl', 'Patel Clay (0-1)', 'MT'),
  ('Pmmpl', 'Patel Clay (1-3)', 'MT'),
  ('Pmmpl', 'Patel Clay (3-5)', 'MT'),
  ('Pmmpl', 'Grog 60% Lumps', 'MT'),
  ('Pmmpl', 'Grog 60% (0-1)', 'MT'),
  ('Pmmpl', 'Grog 60% (1-3)', 'MT'),
  ('Pmmpl', 'Grog 60% (3-5)', 'MT'),
  ('Pmmpl', 'Grog 70% (0-1)', 'MT'),
  ('Pmmpl', 'Grog 70% (1-3)', 'MT'),
  ('Pmmpl', 'Grog 70% (3-5)', 'MT'),
  ('Pmmpl', 'Ferro Chrome Slag', 'MT'),
  ('Pmmpl', 'Ferro Chrome (0-1)', 'MT'),
  ('Pmmpl', 'Ferro Chrome (1-3)', 'MT'),
  ('Pmmpl', 'Ferro Chrome (3-5)', 'MT'),
  ('Pmmpl', 'NRM Lumps', 'MT'),
  ('Pmmpl', '(NRM) (0-1)', 'PCS'),
  ('Pmmpl', '(NRM) (1-3)', 'PCS'),
  ('Pmmpl', '(NRM) (3-5)', 'KG'),
  ('Pmmpl', 'SM 70 (0-1)', 'MT'),
  ('Pmmpl', 'SM 70 (1-3)', 'MT'),
  ('Pmmpl', 'SM 70 (3-5)', 'MT'),
  ('Pmmpl', 'SM 70 (5-8)', 'MT'),
  ('Pmmpl', 'P8', 'MT'),
  ('Pmmpl', 'P14 Clinker', 'MT'),
  ('Pmmpl', 'P14 Fines', 'MT'),
  ('Pmmpl', 'Plastic Clay', 'MT'),
  ('Pmmpl', 'Pp Bag (50 kgs)', 'MT'),
  ('Pmmpl', 'PP Bag (25 kgs)', 'MT'),
  ('Pmmpl', 'Ton Bag(1 Ton)', 'KG'),
  ('Pmmpl', 'Silliminite Sand', 'MT'),
  ('Pmmpl', 'HGRM 30', 'MT'),
  ('Pmmpl', 'MR 04', 'MT'),
  ('Pmmpl', 'SHMP', 'MT'),
  ('Pmmpl', 'PPF', 'MT'),
  ('Pmmpl', 'SSF 304', 'MT'),
  ('Pmmpl', 'SSF 310', 'MT'),
  ('Pmmpl', 'Jole Liquid', 'MT'),
  ('Pmmpl', 'Grinding Media', 'MT'),
  ('Pmmpl', 'Insulation Grog', 'MT'),
  ('Pmmpl', 'WFA -200', 'MT'),
  ('Pmmpl', 'WFA (0-1)', 'MT'),
  ('Pmmpl', 'WFA (1-3)', 'MT'),
  ('Pmmpl', 'WFA (3-5)', 'MT'),
  ('Pmmpl', 'WFA (5-8)', 'PCS'),
  ('Pmmpl', 'WFA(-)16+30', 'MT'),
  ('Pmmpl', 'WFA(-)30# (+)72#', 'MT'),
  ('Pmmpl', 'WFA(-)72# (+)200#', 'MT'),
  ('Pmmpl', 'Tabular Alumina 325Mesh', 'MT'),
  ('Pmmpl', 'Ball Clay Fines', 'MT'),
  ('Pmmpl', 'Hydrated Allumina', 'MT'),
  ('Pmmpl', 'High Alumina 60% Balls', 'MT'),
  ('Pmmpl', 'Pulux V', 'MT'),
  ('Pmmpl', 'Synthetic Slag', 'MT'),
  ('Pmmpl', 'Wastage Material', 'MT'),

  -- Rkl
  ('Rkl', 'GBXT 82 (0-1)', 'MT'),
  ('Rkl', 'GBXT 82 (1-3)', 'MT'),
  ('Rkl', 'GBXT 82 (3-5)', 'MT'),
  ('Rkl', 'GBXT 82 (5-8)', 'MT'),
  ('Rkl', 'GBXT82 FINES', 'MT'),
  ('Rkl', '85% Grog', 'MT'),
  ('Rkl', 'CBXT 89 (0-1)', 'MT'),
  ('Rkl', 'CBXT 89 (1-3)', 'MT'),
  ('Rkl', 'CBXT 89 (3-5)', 'MT'),
  ('Rkl', 'CBXT 89 (5-8)', 'MT'),
  ('Rkl', 'CBXT 89+99C', 'MT'),
  ('Rkl', 'CBXT 89 Fines', 'MT'),
  ('Rkl', '99 C Fired', 'MT'),
  ('Rkl', '99 C Green', 'MT'),
  ('Rkl', '99 C Fines', 'MT'),
  ('Rkl', 'Ferro Chrome Slag', 'MT'),
  ('Rkl', 'BFA (0-1)', 'MT'),
  ('Rkl', 'BFA (1-3)', 'MT'),
  ('Rkl', 'BFA (3-5)', 'MT'),
  ('Rkl', 'BFA (5-8)', 'MT'),
  ('Rkl', 'BFA (-) 325 Mesh', 'MT'),
  ('Rkl', 'BFA -30mesh', 'MT'),
  ('Rkl', 'BFA -46mesh', 'MT'),
  ('Rkl', 'Birla White Cement', 'MT'),
  ('Rkl', 'Cal. Alumina', 'MT'),
  ('Rkl', 'Ceramic Blanket 128 Den', 'PCS'),
  ('Rkl', 'Ceramic Paper 10Mm', 'PCS'),
  ('Rkl', 'Ceramic Paper 5Mm', 'PCS'),
  ('Rkl', 'Ceramic Paper 3MM', 'PCS'),
  ('Rkl', 'Citric Acid', 'LITER'),
  ('Rkl', 'Flyash', 'MT'),
  ('Rkl', 'GBXT 76 (0-1)', 'MT'),
  ('Rkl', 'GBXT 76 (1-3)', 'MT'),
  ('Rkl', 'GBXT 76 (3-5)', 'MT'),
  ('Rkl', 'GBXT 76 (5-8)', 'MT'),
  ('Rkl', 'GBXT 76 Fines', 'MT'),
  ('Rkl', 'HGRM 30', 'MT'),
  ('Rkl', 'Hydrated Alumina', 'MT'),
  ('Rkl', 'Hydrated Alumina Green', 'MT'),
  ('Rkl', 'Hydrated Alumina Fines', 'MT'),
  ('Rkl', 'Imfa Balls', 'MT'),
  ('Rkl', 'Insulator Lumps', 'MT'),
  ('Rkl', 'Jole Liquid', 'LITER'),
  ('Rkl', 'Light Diesel Oil', 'LITER'),
  ('Rkl', 'Lime', 'MT'),
  ('Rkl', 'Low Cailcined Alumina', 'MT'),
  ('Rkl', 'P-8 Fines', 'MT'),
  ('Rkl', 'P-8 Fired', 'MT'),
  ('Rkl', 'P-8 Green', 'MT'),
  ('Rkl', 'P-14', 'MT'),
  ('Rkl', 'P-14 Fines', 'MT'),
  ('Rkl', 'P14 Clinker', 'MT'),
  ('Rkl', 'P-14 Green', 'MT'),
  ('Rkl', 'Plastic Clay', 'MT'),
  ('Rkl', 'Pp Bag (50 kgs)', 'PCS'),
  ('Rkl', 'PP Bag (25 kgs)', 'PCS'),
  ('Rkl', 'Ppf', 'MT'),
  ('Rkl', 'Pyro (0-1)', 'MT'),
  ('Rkl', 'Pyro (1-3)', 'MT'),
  ('Rkl', 'Pyro (3-5)', 'MT'),
  ('Rkl', 'Pyro Fines', 'MT'),
  ('Rkl', 'Insulation Grog', 'MT'),
  ('Rkl', 'Secar 68V', 'MT'),
  ('Rkl', 'SHMP', 'MT'),
  ('Rkl', 'Silliminite Sand', 'MT'),
  ('Rkl', 'SM 70 (0-1)', 'MT'),
  ('Rkl', 'SM 70 (1-3)', 'MT'),
  ('Rkl', 'SM 70 (3-5)', 'MT'),
  ('Rkl', 'SM 70 (5-8)', 'MT'),
  ('Rkl', 'SMC58 60 MESH', 'MT'),
  ('Rkl', 'SMC 58 (0-1)', 'MT'),
  ('Rkl', 'SMC 58 (1-3)', 'MT'),
  ('Rkl', 'SMC 58 (3-5)', 'MT'),
  ('Rkl', 'SMC 58 (5-8)', 'MT'),
  ('Rkl', 'SSF 304', 'MT'),
  ('Rkl', 'SSF 310', 'MT'),
  ('Rkl', 'Tabular Allumina 325mesh', 'MT'),
  ('Rkl', 'Vermicullite', 'MT'),
  ('Rkl', 'Wfa -200', 'MT'),
  ('Rkl', 'WFA(-)16+30', 'MT'),
  ('Rkl', 'WFA (0.5-1)', 'MT'),
  ('Rkl', 'WFA (0-1)', 'MT'),
  ('Rkl', 'WFA (1-2)', 'MT'),
  ('Rkl', 'WFA (1-3)', 'MT'),
  ('Rkl', 'WFA (2-3)', 'MT'),
  ('Rkl', 'WFA (3-5)', 'MT'),
  ('Rkl', 'WFA (5-8)', 'MT'),
  ('Rkl', 'WFA Fines', 'MT'),
  ('Rkl', 'WFA(-)30# (+)72#', 'MT'),
  ('Rkl', 'WFA(-)72# (+)200#', 'MT'),
  ('Rkl', 'WFA Crust', 'MT'),
  ('Rkl', '40% Grog', 'MT'),
  ('Rkl', 'Perlite', 'MT'),
  ('Rkl', 'Portland Cement', 'MT'),
  ('Rkl', '230H Green', 'PCS'),
  ('Rkl', '365H Green', 'PCS'),
  ('Rkl', 'Insulation Pad 250X250X50 Green', 'PCS'),
  ('Rkl', 'Insulation Pad 250X250X75 Green', 'PCS'),
  ('Rkl', 'Low Cailcined Alumina Fines', 'MT'),
  ('Rkl', 'PCPF Hearth Block (600x300x150MM) Green', 'MT'),
  ('Rkl', 'R Bxt Fines', 'MT'),
  ('Rkl', 'Insulator Low', 'MT'),
  ('Rkl', 'MR04', 'MT'),
  ('Rkl', 'Quartz Fines', 'MT'),
  ('Rkl', '97% DBM Fines', 'MT'),
  ('Rkl', '97% DBM (1-3)', 'MT'),
  ('Rkl', '97% DBM (0-1)', 'MT'),
  ('Rkl', 'Rej. Castable Grog', 'MT'),
  ('Rkl', 'P8', 'MT'),
  ('Rkl', 'Ball Clay Fines', 'MT'),
  ('Rkl', '92% Ball (0-1)', 'MT'),
  ('Rkl', '92% Ball (1-3)', 'MT'),
  ('Rkl', '92% Ball (3-5)', 'MT'),
  ('Rkl', 'Catalyst', 'MT'),
  ('Rkl', '90% pre cast', 'MT'),
  ('Rkl', '(NRM) (0-1)', 'MT'),
  ('Rkl', '(NRM) (1-3)', 'MT'),
  ('Rkl', '(NRM) (3-5)', 'MT'),
  ('Rkl', 'NRM Lumps', 'MT'),
  ('Rkl', '70% Mullite(0-5)', 'MT'),
  ('Rkl', '75% calcined Bauxite(0-5)', 'MT'),
  ('Rkl', 'High Microsilica', 'MT'),
  ('Rkl', '90% Brick(0-1)', 'MT'),
  ('Rkl', '90% Brick(1-3)', 'MT'),
  ('Rkl', '90% Brick(3-5)', 'MT'),
  ('Rkl', 'Precast Castable(0-5)', 'MT'),
  ('Rkl', 'Patel Clay (0-1)', 'MT'),
  ('Rkl', 'Patel Clay (1-3)', 'MT'),
  ('Rkl', 'Patel Clay (3-5)', 'MT'),
  ('Rkl', 'Black Cal Bxt Fines', 'MT'),
  ('Rkl', 'R. Bxt. Lumps', 'MT'),
  ('Rkl', 'SRM50(0-1)', 'MT'),
  ('Rkl', 'SRM50(1-3)', 'MT'),
  ('Rkl', 'SRM50(3-5)', 'MT'),
  ('Rkl', 'SRM50(5-8)', 'MT'),
  ('Rkl', 'Cumi Insu Fines', 'MT'),
  ('Rkl', 'Silicone Carbide', 'MT'),
  ('Rkl', 'Old & Used Alumina Brick Grog', 'MT'),
  ('Rkl', '86% Bauxite (0-1)', 'MT'),
  ('Rkl', '86% Bauxite (3-5)', 'MT'),
  ('Rkl', '85% Bauxite (0-1)', 'MT'),
  ('Rkl', '85% Bauxite (1-3)', 'MT'),
  ('Rkl', '84% Cal. Bxt. (0-1)', 'MT'),
  ('Rkl', '84% Cal. Bxt. (1-3)', 'MT'),
  ('Rkl', '84% Cal. Bxt. (3-5)', 'MT'),
  ('Rkl', '84% Cal. Bxt. (5-8)', 'MT'),
  ('Rkl', 'Grog 70% Lumps', 'MT'),
  ('Rkl', 'Grog 60% Lumps', 'MT'),
  ('Rkl', 'Cal. Alumina Fines', 'MT'),
  ('Rkl', '89% Bauxite (6-12)', 'MT'),
  ('Rkl', 'Cumi Insu Grog', 'MT'),
  ('Rkl', 'Katni BXT Fines', 'MT'),
  ('Rkl', 'Grog 60% (0-1)', 'MT'),
  ('Rkl', 'Grog 60% (1-3)', 'MT'),
  ('Rkl', 'Grog 60% (3-5)', 'MT'),
  ('Rkl', 'Grog 70% (0-1)', 'MT'),
  ('Rkl', 'Grog 70% (1-3)', 'MT'),
  ('Rkl', 'Grog 70% (3-5)', 'MT'),
  ('Rkl', 'Ferro Chrome (0-1)', 'MT'),
  ('Rkl', 'Ferro Chrome (1-3)', 'MT'),
  ('Rkl', 'Ferro Chrome (3-5)', 'MT'),
  ('Rkl', 'Insulator (0-1)', 'MT'),
  ('Rkl', 'Insulator (1-3)', 'MT'),
  ('Rkl', 'Insulator (3-5)', 'MT'),
  ('Rkl', 'Ton Bag(1 Ton)', 'MT'),

  -- Purab
  ('Purab', '99 C Fired', 'MT'),
  ('Purab', '99 C Fines', 'MT'),
  ('Purab', 'Smt Sand Fines', 'MT'),
  ('Purab', 'FLYASH', 'MT'),
  ('Purab', 'CBXT 89 Fines', 'MT'),
  ('Purab', 'CBXT 89 (0-1)', 'MT'),
  ('Purab', 'CBXT 89 (1-3)', 'MT'),
  ('Purab', 'CBXT 89 (3-5)', 'MT'),
  ('Purab', 'CBXT 89 (5-8)', 'MT'),
  ('Purab', 'CBXT 89+99C', 'MT'),
  ('Purab', 'GBXT 76 (0-1)', 'MT'),
  ('Purab', 'GBXT 76 (1-3)', 'MT'),
  ('Purab', 'GBXT 76 (3-5)', 'MT'),
  ('Purab', 'GBXT 76 (5-8)', 'MT'),
  ('Purab', 'GBXT 76 Fines', 'MT'),
  ('Purab', 'GBXT 82 (0-1)', 'MT'),
  ('Purab', 'GBXT 82 (1-3)', 'MT'),
  ('Purab', 'GBXT 82 (3-5)', 'MT'),
  ('Purab', 'GBXT 82 (5-8)', 'MT'),
  ('Purab', 'GBXT 82 FINES', 'MT'),
  ('Purab', 'Insulator Lumps', 'MT'),
  ('Purab', 'Insulator (0-1)', 'MT'),
  ('Purab', 'Insulator (1-3)', 'MT'),
  ('Purab', 'Insulator (3-5)', 'MT'),
  ('Purab', 'Ferro Chrome Slag', 'MT'),
  ('Purab', 'Ferro Chrome (0-1)', 'MT'),
  ('Purab', 'Ferro Chrome (1-3)', 'MT'),
  ('Purab', 'Ferro Chrome (3-5)', 'MT'),
  ('Purab', 'Patel Clay (0-1)', 'MT'),
  ('Purab', 'Patel Clay (1-3)', 'MT'),
  ('Purab', 'Patel Clay (3-5)', 'MT'),
  ('Purab', 'Pyro Fines', 'MT'),
  ('Purab', 'Pyro (0-1)', 'MT'),
  ('Purab', 'Pyro (1-3)', 'MT'),
  ('Purab', 'Pyro (3-5)', 'MT'),
  ('Purab', 'High Microsilica', 'MT'),
  ('Purab', 'Low Microsilica', 'MT'),
  ('Purab', 'P14 Clinker', 'MT'),
  ('Purab', 'P14 Fines', 'MT'),
  ('Purab', 'P8', 'MT'),
  ('Purab', 'HGRM 30', 'MT'),
  ('Purab', 'MR04', 'MT'),
  ('Purab', 'Insulation Grog', 'PCS'),
  ('Purab', 'Cumi insu grog', 'PCS'),
  ('Purab', 'Cumi insulation Fines', 'PCS'),
  ('Purab', 'LBX Grains', 'MT'),
  ('Purab', 'LBX Fines', 'MT'),
  ('Purab', 'Imfa Balls', 'MT'),
  ('Purab', 'Siliminite Sand', 'MT'),
  ('Purab', 'Katni BXT Fines', 'MT'),
  ('Purab', 'Black Cal Bxt Fines', 'MT'),
  ('Purab', 'SHMP', 'MT'),
  ('Purab', 'PPF', 'MT'),
  ('Purab', 'Plastic Clay', 'MT'),
  ('Purab', 'Rejected Castable', 'MT'),
  ('Purab', 'Pp Bag (50 kgs)', 'MT'),
  ('Purab', 'PP BAG B - 25', 'MT'),
  ('Purab', 'PP BAG R - 25', 'MT'),
  ('Purab', 'PP BAG 25KG', 'MT'),
  ('Purab', 'LC - 45 E Bag (25 kgs)', 'MT'),
  ('Purab', 'Pasheat-CLC PP Bags 25 Kg', 'MT'),
  ('Purab', 'Ton Bag(1 Ton)', 'MT'),
  ('Purab', 'Birla White Cement', 'MT'),
  ('Purab', 'Citric Acid', 'MT'),
  ('Purab', 'SSF 304', 'MT'),
  ('Purab', 'SSF 310', 'MT'),
  ('Purab', 'Grog 60% Lumps', 'MT'),
  ('Purab', 'Grog 60% (0-1)', 'MT'),
  ('Purab', 'Grog 60% (1-3)', 'PCS'),
  ('Purab', 'Grog 60% (3-5)', 'PCS'),
  ('Purab', 'Grog 70% Lumps', 'MT'),
  ('Purab', 'Grog 70% (0-1)', 'MT'),
  ('Purab', 'Grog 70% (1-3)', 'MT'),
  ('Purab', 'Grog 70% (3-5)', 'MT'),
  ('Purab', 'NRM Lumps', 'MT'),
  ('Purab', '(NRM) (0-1)', 'MT'),
  ('Purab', '(NRM) (1-3)', 'MT'),
  ('Purab', '(NRM) (3-5)', 'MT'),
  ('Purab', 'SM 70 (0-1)', 'MT'),
  ('Purab', 'SM 70 (1-3)', 'MT'),
  ('Purab', 'SM 70 (3-5)', 'MT'),
  ('Purab', 'SM 70 (5-8)', 'MT'),
  ('Purab', 'WFA (0-1)', 'KG'),
  ('Purab', 'WFA (1-3)', 'MT'),
  ('Purab', 'WFA (3-5)', 'MT'),
  ('Purab', 'WFA (5-8)', 'MT'),
  ('Purab', 'WTA (0-1)', 'MT'),
  ('Purab', 'WTA (1-3)', 'MT'),
  ('Purab', 'WTA (3-5)', 'MT'),
  ('Purab', 'BFA (0-1)', 'MT'),
  ('Purab', 'BFA (1-3)', 'MT'),
  ('Purab', 'BFA (3-5)', 'MT'),
  ('Purab', 'BFA (5-8)', 'MT'),
  ('Purab', 'Jole Liquid', 'LTR'),
  ('Purab', 'Tabular Allumina 325mesh', 'MT'),
  ('Purab', 'Hydrated Alumina', 'MT'),
  ('Purab', 'SB90 Fines', 'MT'),
  ('Purab', 'SB 90 (0-1)', 'MT'),
  ('Purab', 'SB 90 (1-3)', 'MT'),
  ('Purab', 'SB 90 (3-5)', 'MT'),
  ('Purab', 'SB 90 (5-8)', 'MT'),
  ('Purab', 'SB70 (1-3)', 'MT'),
  ('Purab', 'SB80 Fines', 'MT'),
  ('Purab', 'SB 80 (0-1)', 'MT'),
  ('Purab', 'SB 80 (1-3)', 'MT'),
  ('Purab', 'SB 80 (3-5)', 'MT'),
  ('Purab', 'SB 70 Fines', 'MT'),
  ('Purab', 'SB 70 (0-1)', 'MT'),
  ('Purab', 'SB 70 (3-5)', 'MT'),
  ('Purab', 'MC - 82 Fines', 'MT'),
  ('Purab', 'MC - 82 (0-1)', 'MT'),
  ('Purab', 'MC - 82 (1-3)', 'MT'),
  ('Purab', 'MC - 82 (3-5)', 'MT')
on conflict (firm_name, item_name) do update
set unit = excluded.unit;

-- Items where unit was not provided. They are still inserted with blank unit.
insert into public.inventory_master (firm_name, item_name, unit)
values
  -- Pmmpl blank-unit items
  ('Pmmpl', 'BFA (-) 325 Mesh', ''),
  ('Pmmpl', 'BFA (0-1)', ''),
  ('Pmmpl', 'BFA (1-3)', ''),
  ('Pmmpl', 'BFA (3-5)', ''),
  ('Pmmpl', 'BFA (5-8)', ''),
  ('Pmmpl', 'Insulator Grains', ''),
  ('Pmmpl', 'Hydrated Allumina Fines', ''),
  ('Pmmpl', 'WFA Fines', ''),
  ('Pmmpl', 'Refra Castable Lumps', ''),
  ('Pmmpl', 'Refra Castable (0-1)', ''),
  ('Pmmpl', 'Refra Castable (1-3)', ''),
  ('Pmmpl', 'Refra Castable (3-5)', ''),
  ('Pmmpl', 'Refra Castable (5-8)', ''),
  ('Pmmpl', 'Kiln ACR', ''),
  ('Pmmpl', 'MC - 82 Lumps', ''),
  ('Pmmpl', 'MC- 82 Fines', ''),
  ('Pmmpl', 'MC - 82 (0-1)', ''),
  ('Pmmpl', 'MC - 82 (1-3)', ''),
  ('Pmmpl', 'MC - 82 (3-5)', ''),
  ('Pmmpl', 'MC - 82 (5-8)', ''),
  ('Pmmpl', 'MC - 82 (3-8)', ''),
  ('Pmmpl', 'MC 82 + SB 90 60mesh', ''),
  ('Pmmpl', 'Allumina Grog (0-1)', ''),
  ('Pmmpl', 'MC 82 60 Mesh', ''),
  ('Pmmpl', 'MC- 90 Fines', ''),
  ('Pmmpl', 'MC-90 Lumps', ''),
  ('Pmmpl', 'MC90 (0-1)', ''),
  ('Pmmpl', 'MC90 (1-3)', ''),
  ('Pmmpl', 'MC90 (3-5)', ''),
  ('Pmmpl', 'MC90 (5-8)', ''),
  ('Pmmpl', 'MC90 (3-8)', ''),
  ('Pmmpl', 'MC 90 60 Mesh', ''),
  ('Pmmpl', 'MC90+MC80 Fines', ''),
  ('Pmmpl', 'MC90+99C Fines', ''),
  ('Pmmpl', 'MC- 80 Fines', ''),
  ('Pmmpl', 'MC-80 Lumps', ''),
  ('Pmmpl', 'MC80 (0-1)', ''),
  ('Pmmpl', 'MC80 (1-3)', ''),
  ('Pmmpl', 'MC80 (3-5)', ''),
  ('Pmmpl', 'MC80 (5-8)', ''),
  ('Pmmpl', 'MC80 (3-8)', ''),
  ('Pmmpl', 'MC 80 60 Mesh', ''),
  ('Pmmpl', 'MC- 70 Fines', ''),
  ('Pmmpl', 'MC-70 Lumps', ''),
  ('Pmmpl', 'MC70 (0-1)', ''),
  ('Pmmpl', 'MC70 (1-3)', ''),
  ('Pmmpl', 'MC70 (3-5)', ''),
  ('Pmmpl', 'MC70 (5-8)', ''),
  ('Pmmpl', 'MC70 (3-8)', ''),
  ('Pmmpl', 'MC 70 60 Mesh', ''),
  ('Pmmpl', 'MC- 40 Fines', ''),
  ('Pmmpl', 'MC-40 Lumps', ''),
  ('Pmmpl', 'MC40 (0-1)', ''),
  ('Pmmpl', 'MC40 (1-3)', ''),
  ('Pmmpl', 'MC40 (3-5)', ''),
  ('Pmmpl', 'MC40 (5-8)', ''),
  ('Pmmpl', 'MC40 (3-8)', ''),
  ('Pmmpl', 'MC 40 60 Mesh', ''),
  ('Pmmpl', 'MC- 95 Fines', ''),
  ('Pmmpl', 'MC-95 Lumps', ''),
  ('Pmmpl', 'MC95 (0-1)', ''),
  ('Pmmpl', 'MC95 (1-3)', ''),
  ('Pmmpl', 'MC95 (3-5)', ''),
  ('Pmmpl', 'MC95 (5-8)', ''),
  ('Pmmpl', 'MC95 (3-8)', ''),
  ('Pmmpl', 'MC 95 60 Mesh', ''),
  ('Pmmpl', 'MC95+MC90 Fines', ''),
  ('Pmmpl', 'NRM Scrap', ''),
  ('Pmmpl', 'Tabular Alumina', ''),
  ('Pmmpl', 'Wastage (0-1)', ''),
  ('Pmmpl', 'Wastage (1-3)', ''),
  ('Pmmpl', 'Wastage  (3-5)', ''),
  ('Pmmpl', 'Wastage  (5-8)', ''),
  ('Pmmpl', '(NRM) (3-8)', ''),
  ('Pmmpl', 'WTA (0-1)', ''),
  ('Pmmpl', 'WTA (1-3)', ''),
  ('Pmmpl', 'WTA (3-5)', ''),
  ('Pmmpl', 'WTA (5-8)', ''),
  ('Pmmpl', 'Kiln ACR-88', ''),
  ('Pmmpl', 'MC-88 Lumps', ''),
  ('Pmmpl', 'MC88 (0-1)', ''),
  ('Pmmpl', 'MC88 (1-3)', ''),
  ('Pmmpl', 'MC88 (3-5)', ''),
  ('Pmmpl', 'MC88 (5-8)', ''),
  ('Pmmpl', 'MC88 (3-8)', ''),
  ('Pmmpl', 'MC-90 (UF)', ''),
  ('Pmmpl', 'MC-90 (S)', ''),
  ('Pmmpl', 'MC - 90 PROCESSED', ''),
  ('Pmmpl', 'Sand Fines', ''),
  ('Pmmpl', 'Kiln Castable Lumps', ''),
  ('Pmmpl', 'Kiln Castable (0-1)', ''),
  ('Pmmpl', 'Kiln Castable (1-3)', ''),
  ('Pmmpl', 'Kiln Castable (3-5)', ''),
  ('Pmmpl', 'Kiln Castable (5-8)', ''),
  ('Pmmpl', 'BACK FILTER FINES', ''),

  -- Rkl blank-unit items
  ('Rkl', 'WTA (0-1)', ''),
  ('Rkl', 'WTA (1-3)', ''),
  ('Rkl', 'WTA (3-5)', ''),
  ('Rkl', 'WTA (5-8)', ''),
  ('Rkl', '97% DBM (3-5)', ''),
  ('Rkl', 'Low Microsilica', ''),
  ('Rkl', 'Micorsilica Sms (E-O)', ''),
  ('Rkl', 'SB90 Lumps', ''),
  ('Rkl', 'SB90 60 Mesh', ''),
  ('Rkl', 'SB90 (0-1)', ''),
  ('Rkl', 'SB90 (1-3)', ''),
  ('Rkl', 'SB90 (3-5)', ''),
  ('Rkl', 'SB90 (5-8)', ''),
  ('Rkl', 'SB90 Fines', ''),
  ('Rkl', '70% Fines', ''),
  ('Rkl', 'Sand Fines', ''),
  ('Rkl', 'Zircon Sand', ''),
  ('Rkl', 'Zircon Fines', ''),
  ('Rkl', 'SB 70 Lumps', ''),
  ('Rkl', 'SB 70 60MESH', ''),
  ('Rkl', 'SB 70 (0-1)', ''),
  ('Rkl', 'SB 70 (1-3)', ''),
  ('Rkl', 'SB 70 (3-5)', ''),
  ('Rkl', 'SB 70 (5-8)', ''),
  ('Rkl', 'SB 70 Fines', ''),
  ('Rkl', 'SB 80 Lumps', ''),
  ('Rkl', 'SB 80 (0-1)', ''),
  ('Rkl', 'SB 80 (1-3)', ''),
  ('Rkl', 'SB 80 (3-5)', ''),
  ('Rkl', 'SB 80 (5-8)', ''),
  ('Rkl', 'SB 80 Fines', ''),
  ('Rkl', 'Insulating Castable', ''),
  ('Rkl', 'MC - 82', ''),
  ('Rkl', 'MC - 82 60Mesh', ''),
  ('Rkl', 'MC - 82 (0-1)', ''),
  ('Rkl', 'MC - 82 (1-3)', ''),
  ('Rkl', 'MC - 82 (3-5)', ''),
  ('Rkl', 'MC - 82 (5-8)', ''),
  ('Rkl', 'MC - 82 Fines', ''),
  ('Rkl', 'MC - 90', ''),
  ('Rkl', 'MC - 90 Fines', ''),
  ('Rkl', 'MC - 90 (0-1)', ''),
  ('Rkl', 'MC - 90 (1-3)', ''),
  ('Rkl', 'MC - 90 (3-5)', ''),
  ('Rkl', 'MC - 90 (5-8)', ''),
  ('Rkl', 'MC 90 Processed', ''),
  ('Rkl', 'MC - 90 Fired', ''),
  ('Rkl', 'MC - 90 Green', ''),
  ('Rkl', 'HAG Blocks Green', ''),
  ('Rkl', 'MC - 82 (S)', ''),
  ('Rkl', 'MC - 82 Green', ''),
  ('Rkl', 'MC - 82 Fired', ''),

  -- Purab blank-unit items
  ('Purab', 'Grog 70% Fines', ''),
  ('Purab', 'WTA Fines', ''),
  ('Purab', 'SB 80 (5-8)', ''),
  ('Purab', 'SB 70 (5-8)', ''),
  ('Purab', 'SB 70 Lumps', ''),
  ('Purab', 'SM 70-R', ''),
  ('Purab', 'Ball Clay Fines', ''),
  ('Purab', 'MC - 82 Lumps', ''),
  ('Purab', 'MC - 82 (5-8)', ''),
  ('Purab', 'MC - 90 Lumps', ''),
  ('Purab', 'MC - 90 Fines', ''),
  ('Purab', 'MC - 90 (0-1)', ''),
  ('Purab', 'MC - 90 (1-3)', ''),
  ('Purab', 'MC - 90 (3-5)', ''),
  ('Purab', 'MC - 90 (5-8)', ''),
  ('Purab', 'MC - 88 (0-1)', ''),
  ('Purab', 'MC - 88 (1-3)', ''),
  ('Purab', 'MC - 88 (3-5)', ''),
  ('Purab', 'MC - 70 (3-5)', ''),
  ('Purab', 'Mix Material (0-1)', ''),
  ('Purab', 'Mix Material (1-3)', ''),
  ('Purab', 'Mix Material (3-5)', ''),
  ('Purab', 'Cement', ''),
  ('Purab', 'FAC (0-1)', ''),
  ('Purab', 'FAC (1-3)', ''),
  ('Purab', 'FAC (3-5)', ''),
  ('Purab', 'FBFAC (0-1)', ''),
  ('Purab', 'Rejected Castable (0-1)', ''),
  ('Purab', 'Rejected Castable (1-3)', ''),
  ('Purab', 'Rejected Castable (3-5)', '')
on conflict (firm_name, item_name) do update
set unit = excluded.unit;
